[project]
name = "hajimi-king"
version = "0.0.1-beta"
description = "Grok (xAI) Key Scraper and Validator"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "python-dotenv>=1.1.1",
    "requests>=2.32.4",
]
